### PR TITLE
212 performance issue

### LINKED ISSUE #212: Performance issue
I just tried to get somewhere around 40 students to generate an Xtext grammar at the same time and it crashed the server. As far as I can tell, the Xtext container and possibly even the Docker daemon got killed. The Xtext container would attempt to restart automatically, which would create extra load on the server, together with all clients continuing to poll for console updates.

It would be worth doing some performance testing to work out what we can do to improve this. It may be an issue to do with the polling for successful editor generation, which we should probably change to server-side events / websockets to improve efficiency.

### PR DESCRIPTION
**Pull request by aryaei2000**
Fixes #212

### CODE REVIEW

File: platform/src/EducationPlatformApp.js [hunk 1]
```diff
@@ -460,7 +462,9 @@ class EducationPlatformApp {
                 if (response.editorUrl) {
                     // Language workbench
                     PlaygroundUtility.longNotification("Building editor");
-                    this.checkEditorReady( response.editorStatusUrl, response.editorUrl, action.source.editorPanel, action.source.editorActivity, outputConsole);
+
+                    var socket = null;
+                    this.checkEditorReady(socket, response.editorID, response.editorUrl, action.source.editorPanel, action.source.editorActivity, outputConsole, false);
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:467]: Why is the socket parameter needed? As far as I can tell, it's always treated just like a local variable...

File: platform/src/EducationPlatformApp.js [hunk 2]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
     }
 
     /**
-     * Poll for editor to become available. 
+     * Open a websockets connection to receive status updates on editor build. 
+     * @param {Object} socket - WebSocket object
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:708]: See above. Explain why this parameter is needed or remove it.

File: platform/src/EducationPlatformApp.js [hunk 3]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
      * @param {String} statusUrl - the url for checking the status of the editor panel.
      * @param {String} editorInstanceUrl - the editor instance's url. 
      * @param {String} editorPanelId - the id of the editor panel.
      * @param {String} editorActivityId - TODO remove as this can be found using editorPanelId to save having to specify in config.
      * @param {Panel} logPanel - the panel to log progress to.
+     * @param {Bool} editorReady - whether editor has finished building or not.
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:714]: Ditto. Why is this parameter needed?

File: platform/src/EducationPlatformApp.js [hunk 4]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
+    checkEditorReady(socket, editorID, editorInstanceUrl, editorPanelId, editorActivityId, logPanel, editorReady){
+        socket = new WebSocket(this.wsUri);
+        socket.onopen = function(){
+            socket.send(editorID);
+        };
+
+        socket.onmessage = function(e){
+            var resultData = JSON.parse(e.data);
+            if (resultData.output){
+                    logPanel.setValue(resultData.output);
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:725]: Would be better to append output to avoid the console always jumping to the very end of the text even when nothing has actually changed.

This would require the server sending increments rather than full text. 

I would suggest that we move this into a separate issue, however, so that we can merge the core WebSocket functionality before improving its behaviour.

File: platform/src/EducationPlatformApp.js [hunk 5]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
+                }
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:726]: Indentation error?

File: platform/src/EducationPlatformApp.js [hunk 6]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
+            if(resultData.editorReady){
+                editorReady = true;
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:728]: If I understand correctly, then the only reason this is here is to stop the `onclose()` handler from trying to reconnect the websocket. This doesn't need `editorReady` to be a parameter to the function, a local variable in `checkEditorReady()` would do, too, wouldn't it? That would keep the interface cleaner.

File: platform/src/EducationPlatformApp.js [hunk 7]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
+                socket.close();
                 sessionStorage.setItem( editorPanelId , editorInstanceUrl );
                 this.activityManager.setActivityVisibility(editorActivityId, true);
                 Metro.notify.killAll();
                 PlaygroundUtility.successNotification("Building complete.");
             }
+        }.bind(this);
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:735]: Why do you need to do this binding here but not for the `onopen` handler? (Probably just my lack of understanding of how JS closures work...)

File: platform/src/EducationPlatformApp.js [hunk 8]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
 
-        } else {
-            console.log("ERROR: The editor response could not be checked: " + statusUrl);
-            PlaygroundUtility.errorNotification("Failed to start the editor.");
+        socket.onclose = function(){
+            //reconnect now
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:738]: Add some more explanation of why this is needed and how it is intended to work.

File: platform/src/EducationPlatformApp.js [hunk 9]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
+            if (!editorReady){
+                if(!socket || socket.readyState == 3){
+                    this.checkEditorReady(socket, editorID, editorInstanceUrl, editorPanelId, editorActivityId, logPanel, editorReady);
+                }
+            }
+        }.bind(this);
+
+            
+        if(!socket || socket.readyState == 3){
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:747]: This leads to a stack overflow if the WS server cannot be reached for some reason.

File: platform/src/EducationPlatformApp.js [hunk 10]
```diff
@@ -700,48 +704,48 @@ class EducationPlatformApp {
...
+        }.bind(this);
 
-        } else {
-            console.log("ERROR: The editor response could not be checked: " + statusUrl);
-            PlaygroundUtility.errorNotification("Failed to start the editor.");
+        socket.onclose = function(){
+            //reconnect now
+            if (!editorReady){
+                if(!socket || socket.readyState == 3){
+                    this.checkEditorReady(socket, editorID, editorInstanceUrl, editorPanelId, editorActivityId, logPanel, editorReady);
```
Comment (szschaler) [inline platform/src/EducationPlatformApp.js:741]: I suspect this might lead to some sort of overflow error if the WS server suddenly becomes unavailable. We're not cleaning up the socket we've just created and we are constantly recursively calling `checkEditorReady()`...

Comment (szschaler) [reply platform/src/EducationPlatformApp.js:741]: Also, when would `socket` ever be `NULL`?

File: platform/src/EducationPlatformApp.js (hunk 9 above)
Comment (szschaler) [reply platform/src/EducationPlatformApp.js:747]: Also, when would `socket` ever be `NULL`?

**Review by szschaler — CHANGES_REQUESTED** [review]
Added some questions and thoughts.

In addition, it would be important to document this protocol somewhere suitable in the Wiki.

File: platform/src/EducationPlatformApp.js (hunk 1 above)
Comment (aryaei2000) [reply platform/src/EducationPlatformApp.js]: This is fixed now. Socket is no longer an input parameter.

File: platform/src/EducationPlatformApp.js (hunk 3 above)
Comment (aryaei2000) [reply platform/src/EducationPlatformApp.js]: Removed now. Used it like socket when I had a slightly different implementation and was supposed to act as a guard for recursion. But now it is defined locally in the function.

File: platform/src/EducationPlatformApp.js (hunk 9 above)
Comment (aryaei2000) [reply platform/src/EducationPlatformApp.js:745]: This clause in the conditional can be removed.

Comment (aryaei2000) [reply platform/src/EducationPlatformApp.js:745]: Regarding stack overflow, yes it is possible. Quickest fix for it is to develop the `onerror` case where we can guard recursion with the help of a flag. One scenario which we should add is checking every couple of seconds or every time page is refreshed for web socket server availability.

File: platform/src/EducationPlatformApp.js (hunk 10 above)
Comment (aryaei2000) [reply platform/src/EducationPlatformApp.js]: This won't fall into a never ending recursion because we have the `editorReady` as a guard. If the server doesn't set `editorReady` at all, then the client keeps creating new connections but not at the speed of light! It has to wait for a connection to get dropped before a new one is created, which is usually a matter of a few seconds.

File: platform/src/EducationPlatformApp.js (hunk 9 above)
Comment (szschaler) [reply platform/src/EducationPlatformApp.js:745]: Sounds good to me

File: platform/src/EducationPlatformApp.js (hunk 10 above)
Comment (szschaler) [reply platform/src/EducationPlatformApp.js]: I don't understand this argument. If the server goes down, then `editorReady` won't change value and `socket` will always have `readyState == 3` (because without a server, there's no connection that can be established). So this will just recurse away quickly and lead to a stack overflow.

**Review by szschaler — APPROVED** [review]
